name: Go test
on: [ push ]

jobs:
  test:
    strategy:
      matrix:
        go-versions:
          - 1.15.x
          - 1.16.x
          - 1.18.x
          - 1.19.x
          - 1.20.x
        platform: [ ubuntu-latest ]
    name: Test
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-versions }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Test
        run: go test -v -cover .
